#
# Tabla "apostador"
#

DROP TABLE IF EXISTS `apostador`;
CREATE TABLE `apostador` (
  `Id` smallint(5) DEFAULT NULL,
  `Apostador` varchar(255) DEFAULT NULL,
  UNIQUE KEY `Id` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Datos de Tabla "apostador"
#

INSERT INTO `apostador` VALUES (1,'Silvina'),(2,'Jose'),(3,'Gonzalo'),(4,'Juan');

#
# Tabla "pronostico"
#

DROP TABLE IF EXISTS `pronostico`;
CREATE TABLE `pronostico` (
  `Id` smallint(5) DEFAULT NULL,
  `Apostador` varchar(255) DEFAULT NULL,
  `Ronda` smallint(5) DEFAULT NULL,
  `Equipo1` varchar(255) DEFAULT NULL,
  `ganaEquipo1` varchar(255) DEFAULT NULL,
  `empate` varchar(255) DEFAULT NULL,
  `ganaEquipo2` varchar(255) DEFAULT NULL,
  `Equipo2` varchar(255) DEFAULT NULL,
  UNIQUE KEY `Id` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Datos de Tabla "pronostico"
#

INSERT INTO `pronostico` VALUES (1,'Silvina',1,'CATAR',NULL,'X',NULL,'ECUADOR'),(2,'Silvina',1,'SENEGAL',NULL,'X',NULL,'PAÍSES BAJOS'),(3,'Silvina',1,'CATAR',NULL,'X',NULL,'SENEGAL'),(4,'Silvina',1,'PAÍSES BAJOS',NULL,'X',NULL,'ECUADOR'),(5,'Silvina',1,'ECUADOR',NULL,'X',NULL,'SENEGAL'),(6,'Silvina',1,'PAÍSES BAJOS',NULL,'X',NULL,'CATAR'),(7,'Silvina',2,'INGLATERRA',NULL,'X',NULL,'IRÁN'),(8,'Silvina',2,'ESTADOS UNIDOS',NULL,'X',NULL,'GALES'),(9,'Silvina',2,'GALES',NULL,'X',NULL,'IRÁN'),(10,'Silvina',2,'INGLATERRA',NULL,'X',NULL,'ESTADOS UNIDOS'),(11,'Silvina',2,'GALES',NULL,'X',NULL,'INGLATERRA'),(12,'Silvina',2,'IRÁN',NULL,'X',NULL,'ESTADOS UNIDOS'),(13,'Jose',3,'MÉXICO','X',NULL,NULL,'POLONIA'),(14,'Jose',3,'ARGENTINA',NULL,'X',NULL,'ARABIA SAUDITA'),(15,'Jose',3,'POLONIA',NULL,NULL,'X','ARABIA SAUDITA'),(16,'Jose',3,'ARGENTINA',NULL,NULL,'X','MÉXICO'),(17,'Jose',3,'POLONIA',NULL,'X',NULL,'ARGENTINA'),(18,'Jose',3,'ARABIA SAUDITA','X',NULL,NULL,'MÉXICO'),(19,'Jose',4,'FRANCIA','X',NULL,NULL,'AUSTRALIA'),(20,'Jose',4,'DINAMARCA',NULL,'X',NULL,'TÚNEZ'),(21,'Jose',4,'TÚNEZ',NULL,NULL,'X','AUSTRALIA'),(22,'Jose',4,'FRANCIA',NULL,NULL,'X','DINAMARCA'),(23,'Jose',4,'AUSTRALIA',NULL,'X',NULL,'DINAMARCA'),(24,'Jose',4,'TÚNEZ','X',NULL,NULL,'FRANCIA'),(25,'Gonzalo',5,'ESPAÑA','X',NULL,NULL,'COSTA RICA'),(26,'Gonzalo',5,'ALEMANIA','X',NULL,NULL,'JAPÓN'),(27,'Gonzalo',5,'JAPÓN','X',NULL,NULL,'COSTA RICA'),(28,'Gonzalo',5,'ESPAÑA','X',NULL,NULL,'ALEMANIA'),(29,'Gonzalo',5,'JAPÓN','X',NULL,NULL,'ESPAÑA'),(30,'Gonzalo',5,'COSTA RICA','X',NULL,NULL,'ALEMANIA'),(31,'Gonzalo',6,'BÉLGICA','X',NULL,NULL,'CANADÁ'),(32,'Gonzalo',6,'MARRUECOS','X',NULL,NULL,'CROACIA'),(33,'Gonzalo',6,'BÉLGICA','X',NULL,NULL,'MARRUECOS'),(34,'Gonzalo',6,'CROACIA','X',NULL,NULL,'CANADÁ'),(35,'Gonzalo',6,'CROACIA','X',NULL,NULL,'BÉLGICA'),(36,'Gonzalo',6,'CANADÁ','X',NULL,NULL,'MARRUECOS'),(37,'Juan',7,'SUIZA','X',NULL,NULL,'CAMERÚN'),(38,'Juan',7,'BRASIL','X',NULL,NULL,'SERBIA'),(39,'Juan',7,'CAMERÚN','X',NULL,NULL,'SERBIA'),(40,'Juan',7,'BRASIL','X',NULL,NULL,'SUIZA'),(41,'Juan',7,'SERBIA','X',NULL,NULL,'SUIZA'),(42,'Juan',7,'CAMERÚN','X',NULL,NULL,'BRASIL'),(43,'Juan',8,'URUGUAY','X',NULL,NULL,'COREA DEL SUR'),(44,'Juan',8,'PORTUGAL','X',NULL,NULL,'GHANA'),(45,'Juan',8,'COREA DEL SUR','X',NULL,NULL,'GHANA'),(46,'Juan',8,'PORTUGAL','X',NULL,NULL,'URUGUAY'),(47,'Juan',8,'GHANA','X',NULL,NULL,'URUGUAY'),(48,'Juan',8,'COREA DEL SUR','X',NULL,NULL,'PORTUGAL');

#
# Tabla "resultados"
#

DROP TABLE IF EXISTS `resultados`;
CREATE TABLE `resultados` (
  `Id` smallint(5) DEFAULT NULL,
  `Ronda` smallint(5) DEFAULT NULL,
  `Equipo1` varchar(255) DEFAULT NULL,
  `golesEquipo1` smallint(5) DEFAULT NULL,
  `golesEquipo2` smallint(5) DEFAULT NULL,
  `Equipo2` varchar(255) DEFAULT NULL,
  UNIQUE KEY `Id` (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Datos de Tabla "resultados"
#

INSERT INTO `resultados` VALUES (1,1,'CATAR',0,2,'ECUADOR'),(2,1,'SENEGAL',0,2,'PAÍSES BAJOS'),(3,1,'CATAR',1,3,'SENEGAL'),(4,1,'PAÍSES BAJOS',1,1,'ECUADOR'),(5,1,'ECUADOR',1,2,'SENEGAL'),(6,1,'PAÍSES BAJOS',2,0,'CATAR'),(7,2,'INGLATERRA',6,2,'IRÁN'),(8,2,'ESTADOS UNIDOS',1,1,'GALES'),(9,2,'GALES',0,2,'IRÁN'),(10,2,'INGLATERRA',0,0,'ESTADOS UNIDOS'),(11,2,'GALES',0,3,'INGLATERRA'),(12,2,'IRÁN',0,1,'ESTADOS UNIDOS'),(13,3,'MÉXICO',0,0,'POLONIA'),(14,3,'ARGENTINA',1,2,'ARABIA SAUDITA'),(15,3,'POLONIA',2,0,'ARABIA SAUDITA'),(16,3,'ARGENTINA',2,0,'MÉXICO'),(17,3,'POLONIA',0,2,'ARGENTINA'),(18,3,'ARABIA SAUDITA',1,2,'MÉXICO'),(19,4,'FRANCIA',4,1,'AUSTRALIA'),(20,4,'DINAMARCA',0,0,'TÚNEZ'),(21,4,'TÚNEZ',0,1,'AUSTRALIA'),(22,4,'FRANCIA',2,1,'DINAMARCA'),(23,4,'AUSTRALIA',1,0,'DINAMARCA'),(24,4,'TÚNEZ',1,0,'FRANCIA'),(25,5,'ESPAÑA',7,0,'COSTA RICA'),(26,5,'ALEMANIA',1,2,'JAPÓN'),(27,5,'JAPÓN',0,1,'COSTA RICA'),(28,5,'ESPAÑA',1,1,'ALEMANIA'),(29,5,'JAPÓN',2,1,'ESPAÑA'),(30,5,'COSTA RICA',2,4,'ALEMANIA'),(31,6,'BÉLGICA',1,0,'CANADÁ'),(32,6,'MARRUECOS',0,0,'CROACIA'),(33,6,'BÉLGICA',0,2,'MARRUECOS'),(34,6,'CROACIA',4,1,'CANADÁ'),(35,6,'CROACIA',0,0,'BÉLGICA'),(36,6,'CANADÁ',1,2,'MARRUECOS'),(37,7,'SUIZA',1,0,'CAMERÚN'),(38,7,'BRASIL',2,0,'SERBIA'),(39,7,'CAMERÚN',3,3,'SERBIA'),(40,7,'BRASIL',1,0,'SUIZA'),(41,7,'SERBIA',2,3,'SUIZA'),(42,7,'CAMERÚN',1,0,'BRASIL'),(43,8,'URUGUAY',0,0,'COREA DEL SUR'),(44,8,'PORTUGAL',3,2,'GHANA'),(45,8,'COREA DEL SUR',2,3,'GHANA'),(46,8,'PORTUGAL',2,0,'URUGUAY'),(47,8,'GHANA',0,2,'URUGUAY'),(48,8,'COREA DEL SUR',2,1,'PORTUGAL');
